language: ruby
script: 'bundle exec rake'
gemfile:
  - gemfiles/Gemfile.activesupport-3.x
  - gemfiles/Gemfile.activesupport-4.x
  - gemfiles/Gemfile.activesupport-5.x
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.3
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head
services:
  - redis-server
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.activesupport-5.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activesupport-5.x
    - rvm: 2.1.5
      gemfile: gemfiles/Gemfile.activesupport-5.x
